### ISSUE TITLE
How to use this with java ?

### ISSUE THREAD

**Issue by pankajnitt** [xlvecle/geohash-poly#1]
When i am downloading jar with gradle i am can see only manifest no classes . 
in this jar we have only two files
1) pom.properties
2) pom.xml

**Comment by rossmckelvie** [comment]
same with maven

**Comment by xlvecle** [comment]
I'm so sorry that i upload the error jar to maven repo, I'd fix that on time.

**Comment by xlvecle** [comment]
It has been fixed in release 1.0.4, so sorry for my careless
